### ISSUE TITLE
Is it supported to obtain the teacher's business card

### ISSUE THREAD

**Issue by Jadlokin-Scarlet** [torikushiii/BlueArchiveAPI#1]
Is it supported to obtain the teacher's business card

**Comment by torikushiii** [comment]
I'm not sure what do you mean by "Teacher's business card", could you elaborate more?

**Comment by Jadlokin-Scarlet** [comment]
Such as uid, nickname, grade, profile, avatar, duty student, ranking, etc.
<img width="697" alt="C0FE9BA1-5575-4B8B-A259-9B86D4B87097" src="https://user-images.githubusercontent.com/32767557/172974529-5864322e-b55a-4085-8f32-5dfb6fed911a.png">

**Comment by torikushiii** [comment]
Unfortunately, with how the current game works, I think it's not possible as for now.
