### ISSUE TITLE
Support get all characters

### ISSUE THREAD

**Issue by reykim7854** [torikushiii/BlueArchiveAPI#2]
Hello, would you consider to support the API to be able to get all characters in a list? The payload only need to contain basic information about the characters. Or maybe using a limit for how many characters that can be send through the payload.

**Comment by torikushiii** [comment]
Can you elaborate more on what do you want on characters basic information ?

Do you want their name, school, rarity and such ?

**Comment by reykim7854** [comment]
For starter, I think these information should suffice for the payload
```
"data": [
{
   "baseStar": 3,
   "school": "Gehenna"
   "rarity": "SSR",
   "name": "Aru",
   "armorType": "Light Armor",
   "bulletType": "Explosion",
   "position": "Back",
   "role": "Attacker",
   "squadType": "Striker",
   "weaponType": "SR",
   "terrain": {
            "Urban": {
                "DamageDealt": "120%(1.2x)",
                "ShieldBlockRate": "60%"
            },
            "Desert": {
                "DamageDealt": "100%(1x)",
                "ShieldBlockRate": "30%"
            },
            "Indoor": {
                "DamageDealt": "80%(0.8x)",
                "ShieldBlockRate": "0%"
            }
      }
}
]
```
As you can see, those information is close to the one in-game for student list for the filters. I saw that your API already have the capabilities to get characters with multiple queries with some of those information, so I thought getting list of characters without queries could be the default payload for the endpoint.

**Comment by torikushiii** [comment]
I've deployed the character list as suggested on the [character endpoint](https://api.ennead.cc/buruaka/character/)

Do tell me if this what you wanted.

**Comment by reykim7854** [comment]
Yes, that's exactly what I wanted, thank you very much for considering my feedback.

**Comment by AmeMizuki** [comment]
Sorry bothering and re-opening this issue
But I have a question about why there's no character pics or icon for each characters?

**Comment by torikushiii** [comment]
@LiuWaiting203 this was never meant to be added, but I might be able to add to do that.
