### ISSUE TITLE
Query about data

### ISSUE THREAD

**Issue by sanskar-mk2** [torikushiii/BlueArchiveAPI#3]
Hello, I am curious about how the data is obtained and how can I verify if it is up-to-date.

Will the data be in public repo (as JSON maybe) so everyone can contribute if there is erroneous data?

I am planning to build a small app to help me select team quickly.

Thank you.

**Comment by torikushiii** [comment]
Hello, sorry for the late reply

1. How the data is obtained

- By reverse engineering the game

2. How can you verify if it's up-to-date

- Either you can go to [base URL](https://api.ennead.cc/buruaka/) and check out the version
- Or you can check out on the [README.md](https://github.com/torikushiii/BlueArchiveAPI#readme) under the Hosted API
- Then you can compare it by opening the game and check out on the [top right corner](https://i.imgur.com/VN4eKcy.png) under your UID

3. Will the data be in public repo

- As for this you can use someone [repo](https://github.com/aizawey479/ba-data)

Good luck with your small app :)

**Comment by sanskar-mk2** [comment]
Thanks

**Comment by sanskar-mk2** [comment]
Actually, to add on to this question~
Would it be possible to get the user data through some API?
If I want to make app to select best team for any map then I would have to know the items and levels of my characters.
It would help if there was way to get the data of user and their students, otherwise I would have to manually create and update my user data.

**Comment by torikushiii** [comment]
Unfortunately, as the current game work, there's no way to obtain that data. But this could change in the future
