### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by Mick9555** [torikushiii/BlueArchiveAPI#6]
i'm new to this and idk what i'm doing can you show me remote access anydusk app my discord MichaeLK#0660 it mean a lot if you helped me

**Comment by torikushiii** [comment]
Hi there! I'd be happy to help you. However, granting remote access to your computer is not necessary in this case. I can guide you through the process without the need for remote access.

At what exactly do you need assistance? Are you looking for help with understanding how to use the Blue Archive API, or do you have specific questions about the API endpoints or how to make requests to retrieve the desired data?

**Comment by Mick9555** [comment]
with every thing i'm new to this stuff
can you make a video

**Comment by Mick9555** [comment]
i feel it be more easy with  remote access tho

**Comment by Mick9555** [comment]
hello ?

**Comment by torikushiii** [comment]
Hi yes, sorry for the late reply.

This repo is basically a project that provides an API for the game Blue Archive. It allows users to access character data, banner data, and raid data through API endpoints, enabling developers and gamers to retrieve information about the game's characters, ongoing banners, and available raids programmatically.

For example if you want to see character data named "Aru" you can go to the character endpoint with specifying Aru like this [https://api.ennead.cc/buruaka/character/Aru](https://api.ennead.cc/buruaka/character/Aru)

Or if you wanted to check what's the current banner and the upcoming banner rate ups, you can go to this URL and check it out [https://api.ennead.cc/buruaka/banner](https://api.ennead.cc/buruaka/banner)

You also can check out what's the upcoming raids using this URL [https://api.ennead.cc/buruaka/raid](https://api.ennead.cc/buruaka/raid)

I also have [docs](https://github.com/torikushiii/BlueArchiveAPI/tree/main/docs) for detailed uses.
