### ISSUE TITLE
Add birthdays

### ISSUE THREAD

**Issue by Akamaru** [torikushiii/BlueArchiveAPI#7]
Hi, can you add birthdays of the students?

Thanks for your work!

**Comment by torikushiii** [comment]
Hi,

Yes there's already birthdays of the students being displayed but I put the wrong variable name so it didn't display it properly.

You can check it out now, the data should be in the `info` property

```
"info": {
    "age": "16 years old",
    "height": "160cm",
    "artist": "DoReMi",
    "birthDate": "March 12th",
    "club": "Kohshinjo68",
    "school": "Gehenna",
    "schoolYear": "2nd Year",
    "voiceActor": "近藤玲奈"
  }
  ```
