### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by fuyuSanZ** [torikushiii/BlueArchiveAPI#8]
hi,how about the database?
any example / used structure & data

**Comment by torikushiii** [comment]
for the database structure you can take a look in here

> https://github.com/torikushiii/BlueArchiveAPI/blob/main/core/classes/character.js#L4
```
{
	id: 001,
	rarity: 3,
	armorType: "LightArmor"
	... and so on
}
```

all the related functions should be all in there too

**Comment by sabedegg** [comment]
for dump dbs? :3

**Comment by fuyuSanZ** [comment]
> for the database structure you can take a look in here
> 
> > https://github.com/torikushiii/BlueArchiveAPI/blob/main/core/classes/character.js#L4
> 
> ```
> {
> 	id: 001,
> 	rarity: 3,
> 	armorType: "LightArmor"
> 	... and so on
> }
> ```
> 
> all the related functions should be all in there too

i already input sample data for banner,but i got error data.rateups is not iterable, how to fix it?

**Comment by torikushiii** [comment]
for banner stuff, the `data.rateup` contains an character id array like this

```
{
	id: 00000,
	type: "PickupGacha",
	rateup: [ 1000, 2000 ],
	startAt: start date,
	endAt: end date
}
```

**Comment by fuyuSanZ** [comment]
> for banner stuff, the `data.rateup` contains an character id array like this
> 
> ```
> {
> 	id: 00000,
> 	type: "PickupGacha",
> 	rateup: [ 1000, 2000 ],
> 	startAt: start date,
> 	endAt: end date
> }
> ```

structure for banner only like that?

**Comment by torikushiii** [comment]
yes, forgot to mention that the date are in unix format
